apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: quiz-microservice
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - port: 8765
      targetPort: 8765
      nodePort: 30065

