apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: quiz-microservice
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: nnhainam/mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "642004"
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          #securityContext:
            #runAsUser: 999    # UID mặc định của MySQL 5.7
            #fsGroup: 999
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-scripts
          configMap:
            name: mysql-init-scripts

