apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: quiz-microservice
spec:
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

