apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: quiz-microservice
spec:
  selector:
    app: registry-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30061

