apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: quiz-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
        - name: registry-container
          image: nnhainam/registry-service-img
          ports:
            - containerPort: 8761

