apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-deployment
  namespace: quiz-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-container
          image: nnhainam/quiz-service-img
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: "quizdb"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "642004"
            - name: EUREKA_SERVER_URL
              value: "http://registry-service:8761/eureka"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

